DROP TABLE IF EXISTS PLAYER;
DROP TABLE IF EXISTS TEAM;
DROP TABLE IF EXISTS TRANSFER;

CREATE TABLE PLAYER (
  id_player INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  birth_date VARCHAR(100) NOT NULL,
  nationality VARCHAR(100) NOT NULL,
  id_team INT
);

CREATE TABLE TEAM (
  id_team INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  locality VARCHAR(100) NOT NULL
);

CREATE TABLE TRANSFER (
  id_transfer INT AUTO_INCREMENT  PRIMARY KEY,
  destination_team VARCHAR(100) NOT NULL,
  origin_team VARCHAR(100) NOT NULL,
  date_transfer VARCHAR(100) NOT NULL,
  value_transfer FLOAT NOT NULL
);

ALTER TABLE PLAYER
ADD FOREIGN KEY (id_team) REFERENCES TEAM(id_team)